// ============================================================
// Network
// ============================================================
export const RPC_URL = "https://rpc.lightsail.network";

// ============================================================
// Tokens
// ============================================================
export const USDC_TOKEN = "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75";
export const XLM_TOKEN = "native";  
export const EURC_TOKEN = "CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV";

// ============================================================
// DeFindex Factory
// ============================================================
export const DEFINDEX_FACTORY = "CDKFHFJIET3A73A2YN4KV7NSV32S6YGQMUFH3DNJXLBWL4SKEGVRNFKI";


// ============================================================
// Strategies — Blend Fixed
// ============================================================
export const USDC_BLEND_FIXED_STRATEGY = "CDB2WMKQQNVZMEBY7Q7GZ5C7E7IAFSNMZ7GGVD6WKTCEWK7XOIAVZSAP";
export const EURC_BLEND_FIXED_STRATEGY = "CC5CE6MWISDXT3MLNQ7R3FVILFVFEIH3COWGH45GJKL6BD2ZHF7F7JVI";
export const XLM_BLEND_FIXED_STRATEGY = "CDPWNUW7UMCSVO36VAJSQHQECISPJLCVPDASKHRC5SEROAAZDUQ5DG2Z";

// ============================================================
// Strategies — Blend YieldBlox
// ============================================================
export const USDC_BLEND_YIELDBLOX_STRATEGY = "CCSRX5E4337QMCMC3KO3RDFYI57T5NZV5XB3W3TWE4USCASKGL5URKJL";
export const EURC_BLEND_YIELDBLOX_STRATEGY = "CA33NXYN7H3EBDSA3U2FPSULGJTTL3FQRHD2ADAAPTKS3FUJOE73735A";
export const XLM_BLEND_YIELDBLOX_STRATEGY = "CBDOIGFO2QOOZTWQZ7AFPH5JOUS2SBN5CTTXR665NHV6GOCM6OUGI5KP";
export const CETES_BLEND_YIELDBLOX_STRATEGY = "CBTSRJLN5CVVOWLTH2FY5KNQ47KW5KKU3VWGASDN72STGMXLRRNHPRIL";
export const AQUA_BLEND_YIELDBLOX_STRATEGY = "CCMJUJW6Z7I3TYDCJFGTI3A7QA3ASMYAZ5PSRRWBBIJQPKI2GXL5DW5D";
export const USTRY_BLEND_YIELDBLOX_STRATEGY = "CDDXPBOF727FDVTNV4I3G4LL4BHTJHE5BBC4W6WZAHMUPFDPBQBL6K7Y";
export const USDGLO_BLEND_YIELDBLOX_STRATEGY = "CCTLQXYSIUN3OSZLZ7O7MIJC6YCU3QLLS6TUM3P2CD6DAVELMWC3QV4E";

// ============================================================
// Strategies — Blend Orbit
// ============================================================
export const XLM_BLEND_ORBIT_STRATEGY = "CCY2V6WZDC7UZL225KHUE6YZOM44XCU3CNE5WYQGTDKP67QQ6U6W46UD";
export const USTRY_BLEND_ORBIT_STRATEGY = "CB5FP32DQKDA7Z7SJ7DGP2FRJRQLPXBSRMSK2KNLGC3V4SXWIIWLJWKM";
export const CETES_BLEND_ORBIT_STRATEGY = "CBWD2EKIMVG6PM6VZEOCFJ3HPRZ2MDOIT3JCCK6WX2JURISQ3LWWBUIT";
export const OUSD_BLEND_ORBIT_STRATEGY = "CDXZESX452QH2NIINQDTJ2S7G2CF2QCL43Q3K2VN3VAVKIE4QRS43GHC";

// ============================================================
// Testnet
// ============================================================
export const TESTNET_RPC_URL = "https://soroban-testnet.stellar.org";
export const TESTNET_XLM_SAC = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";
export const TESTNET_DEFINDEX_FACTORY = "CDSCWE4GLNBYYTES2OCYDFQA2LLY4RBIAX6ZI32VSUXD7GO6HRPO4A32";
export const TESTNET_XLM_BLEND_STRATEGY = "CDVLOSPJPQOTB6ZCWO5VSGTOLGMKTXSFWYTUP572GTPNOWX4F76X3HPM";
export const TESTNET_USDC_BLEND_STRATEGY = "CALLOM5I7XLQPPOPQMYAHUWW4N7O3JKT42KQ4ASEEVBXDJQNJOALFSUY";
export const TESTNET_SOROSWAP_ROUTER = "CCJUD55AG6W5HAI5LRVNKAE5WDP5XGZBUDS5WNTIVDU7O264UZZE7BRD";
